apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - env:
        - name: LOCUST_MODE
          value: master
        - name: TARGET_HOST
          value: http://emailerer.com
        image: us.gcr.io/andy-playground-264516/locust-image:latest
        imagePullPolicy: Always
        name: load-test-locust-master
        ports:
        - containerPort: 8089
          name: load-test-web
          protocol: TCP
        - containerPort: 5557
          name: loc-master-p1
          protocol: TCP
        - containerPort: 5558
          name: loc-master-p2
          protocol: TCP
      terminationGracePeriodSeconds: 15
