apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"locust-master","namespace":"default"},"spec":{"replicas":1,"revisionHistoryLimit":5,"template":{"metadata":{"labels":{"app":"load-test","role":"master","track":"locust"}},"spec":{"containers":[{"env":[{"name":"LOCUST_MODE","value":"master"},{"name":"TARGET_HOST","value":"http://emailerer.com"}],"image":"us.gcr.io/andy-playground-264516/locust-image:latest","name":"load-test-locust-master","ports":[{"containerPort":8089,"name":"load-test-web"},{"containerPort":5557,"name":"loc-master-p1"},{"containerPort":5558,"name":"loc-master-p2"}]}]}}}}
  creationTimestamp: "2020-03-25T20:39:28Z"
  generation: 2
  labels:
    app: load-test
    role: master
    track: locust
  name: locust-master
  namespace: default
  resourceVersion: "4294"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/locust-master
  uid: b941efec-6ed8-11ea-a5c6-42010a800079
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: load-test
      role: master
      track: locust
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: load-test
        role: master
        track: locust
    spec:
      containers:
      - env:
        - name: LOCUST_MODE
          value: master
        - name: TARGET_HOST
          value: http://emailerer.com
        image: us.gcr.io/andy-playground-264516/locust-image:latest
        imagePullPolicy: Always
        name: load-test-locust-master
        ports:
        - containerPort: 8089
          name: load-test-web
          protocol: TCP
        - containerPort: 5557
          name: loc-master-p1
          protocol: TCP
        - containerPort: 5558
          name: loc-master-p2
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-25T20:39:28Z"
    lastUpdateTime: "2020-03-25T20:39:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
